// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: qiwen-schema.proto
package org.example.protobuf;

public final class QiwenSchema {
  private QiwenSchema() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface QiwenSchemaInfoOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional int64 id = 1;
    /**
     * <code>optional int64 id = 1;</code>
     */
    boolean hasId();
    /**
     * <code>optional int64 id = 1;</code>
     */
    long getId();

    // optional int64 timestamp = 2;
    /**
     * <code>optional int64 timestamp = 2;</code>
     */
    boolean hasTimestamp();
    /**
     * <code>optional int64 timestamp = 2;</code>
     */
    long getTimestamp();

    // optional int32 field_int32 = 3;
    /**
     * <code>optional int32 field_int32 = 3;</code>
     */
    boolean hasFieldInt32();
    /**
     * <code>optional int32 field_int32 = 3;</code>
     */
    int getFieldInt32();

    // optional float field_float = 4;
    /**
     * <code>optional float field_float = 4;</code>
     */
    boolean hasFieldFloat();
    /**
     * <code>optional float field_float = 4;</code>
     */
    float getFieldFloat();

    // optional double field_double = 5;
    /**
     * <code>optional double field_double = 5;</code>
     */
    boolean hasFieldDouble();
    /**
     * <code>optional double field_double = 5;</code>
     */
    double getFieldDouble();

    // repeated int64 long_array = 6;
    /**
     * <code>repeated int64 long_array = 6;</code>
     */
    java.util.List<java.lang.Long> getLongArrayList();
    /**
     * <code>repeated int64 long_array = 6;</code>
     */
    int getLongArrayCount();
    /**
     * <code>repeated int64 long_array = 6;</code>
     */
    long getLongArray(int index);

    // repeated string string_array = 10;
    /**
     * <code>repeated string string_array = 10;</code>
     */
    java.util.List<java.lang.String>
    getStringArrayList();
    /**
     * <code>repeated string string_array = 10;</code>
     */
    int getStringArrayCount();
    /**
     * <code>repeated string string_array = 10;</code>
     */
    java.lang.String getStringArray(int index);
    /**
     * <code>repeated string string_array = 10;</code>
     */
    com.google.protobuf.ByteString
        getStringArrayBytes(int index);
  }
  /**
   * Protobuf type {@code QiwenSchemaInfo}
   */
  public static final class QiwenSchemaInfo extends
      com.google.protobuf.GeneratedMessage
      implements QiwenSchemaInfoOrBuilder {
    // Use QiwenSchemaInfo.newBuilder() to construct.
    private QiwenSchemaInfo(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private QiwenSchemaInfo(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final QiwenSchemaInfo defaultInstance;
    public static QiwenSchemaInfo getDefaultInstance() {
      return defaultInstance;
    }

    public QiwenSchemaInfo getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private QiwenSchemaInfo(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              id_ = input.readInt64();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              timestamp_ = input.readInt64();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              fieldInt32_ = input.readInt32();
              break;
            }
            case 37: {
              bitField0_ |= 0x00000008;
              fieldFloat_ = input.readFloat();
              break;
            }
            case 41: {
              bitField0_ |= 0x00000010;
              fieldDouble_ = input.readDouble();
              break;
            }
            case 48: {
              if (!((mutable_bitField0_ & 0x00000020) == 0x00000020)) {
                longArray_ = new java.util.ArrayList<java.lang.Long>();
                mutable_bitField0_ |= 0x00000020;
              }
              longArray_.add(input.readInt64());
              break;
            }
            case 50: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              if (!((mutable_bitField0_ & 0x00000020) == 0x00000020) && input.getBytesUntilLimit() > 0) {
                longArray_ = new java.util.ArrayList<java.lang.Long>();
                mutable_bitField0_ |= 0x00000020;
              }
              while (input.getBytesUntilLimit() > 0) {
                longArray_.add(input.readInt64());
              }
              input.popLimit(limit);
              break;
            }
            case 82: {
              if (!((mutable_bitField0_ & 0x00000040) == 0x00000040)) {
                stringArray_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000040;
              }
              stringArray_.add(input.readBytes());
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000020) == 0x00000020)) {
          longArray_ = java.util.Collections.unmodifiableList(longArray_);
        }
        if (((mutable_bitField0_ & 0x00000040) == 0x00000040)) {
          stringArray_ = new com.google.protobuf.UnmodifiableLazyStringList(stringArray_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return QiwenSchema.internal_static_QiwenSchemaInfo_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return QiwenSchema.internal_static_QiwenSchemaInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              QiwenSchema.QiwenSchemaInfo.class, QiwenSchema.QiwenSchemaInfo.Builder.class);
    }

    public static com.google.protobuf.Parser<QiwenSchemaInfo> PARSER =
        new com.google.protobuf.AbstractParser<QiwenSchemaInfo>() {
      public QiwenSchemaInfo parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new QiwenSchemaInfo(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<QiwenSchemaInfo> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // optional int64 id = 1;
    public static final int ID_FIELD_NUMBER = 1;
    private long id_;
    /**
     * <code>optional int64 id = 1;</code>
     */
    public boolean hasId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional int64 id = 1;</code>
     */
    public long getId() {
      return id_;
    }

    // optional int64 timestamp = 2;
    public static final int TIMESTAMP_FIELD_NUMBER = 2;
    private long timestamp_;
    /**
     * <code>optional int64 timestamp = 2;</code>
     */
    public boolean hasTimestamp() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional int64 timestamp = 2;</code>
     */
    public long getTimestamp() {
      return timestamp_;
    }

    // optional int32 field_int32 = 3;
    public static final int FIELD_INT32_FIELD_NUMBER = 3;
    private int fieldInt32_;
    /**
     * <code>optional int32 field_int32 = 3;</code>
     */
    public boolean hasFieldInt32() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional int32 field_int32 = 3;</code>
     */
    public int getFieldInt32() {
      return fieldInt32_;
    }

    // optional float field_float = 4;
    public static final int FIELD_FLOAT_FIELD_NUMBER = 4;
    private float fieldFloat_;
    /**
     * <code>optional float field_float = 4;</code>
     */
    public boolean hasFieldFloat() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional float field_float = 4;</code>
     */
    public float getFieldFloat() {
      return fieldFloat_;
    }

    // optional double field_double = 5;
    public static final int FIELD_DOUBLE_FIELD_NUMBER = 5;
    private double fieldDouble_;
    /**
     * <code>optional double field_double = 5;</code>
     */
    public boolean hasFieldDouble() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional double field_double = 5;</code>
     */
    public double getFieldDouble() {
      return fieldDouble_;
    }

    // repeated int64 long_array = 6;
    public static final int LONG_ARRAY_FIELD_NUMBER = 6;
    private java.util.List<java.lang.Long> longArray_;
    /**
     * <code>repeated int64 long_array = 6;</code>
     */
    public java.util.List<java.lang.Long>
        getLongArrayList() {
      return longArray_;
    }
    /**
     * <code>repeated int64 long_array = 6;</code>
     */
    public int getLongArrayCount() {
      return longArray_.size();
    }
    /**
     * <code>repeated int64 long_array = 6;</code>
     */
    public long getLongArray(int index) {
      return longArray_.get(index);
    }

    // repeated string string_array = 10;
    public static final int STRING_ARRAY_FIELD_NUMBER = 10;
    private com.google.protobuf.LazyStringList stringArray_;
    /**
     * <code>repeated string string_array = 10;</code>
     */
    public java.util.List<java.lang.String>
        getStringArrayList() {
      return stringArray_;
    }
    /**
     * <code>repeated string string_array = 10;</code>
     */
    public int getStringArrayCount() {
      return stringArray_.size();
    }
    /**
     * <code>repeated string string_array = 10;</code>
     */
    public java.lang.String getStringArray(int index) {
      return stringArray_.get(index);
    }
    /**
     * <code>repeated string string_array = 10;</code>
     */
    public com.google.protobuf.ByteString
        getStringArrayBytes(int index) {
      return stringArray_.getByteString(index);
    }

    private void initFields() {
      id_ = 0L;
      timestamp_ = 0L;
      fieldInt32_ = 0;
      fieldFloat_ = 0F;
      fieldDouble_ = 0D;
      longArray_ = java.util.Collections.emptyList();
      stringArray_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt64(1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt64(2, timestamp_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(3, fieldInt32_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeFloat(4, fieldFloat_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeDouble(5, fieldDouble_);
      }
      for (int i = 0; i < longArray_.size(); i++) {
        output.writeInt64(6, longArray_.get(i));
      }
      for (int i = 0; i < stringArray_.size(); i++) {
        output.writeBytes(10, stringArray_.getByteString(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, timestamp_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, fieldInt32_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(4, fieldFloat_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(5, fieldDouble_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < longArray_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeInt64SizeNoTag(longArray_.get(i));
        }
        size += dataSize;
        size += 1 * getLongArrayList().size();
      }
      {
        int dataSize = 0;
        for (int i = 0; i < stringArray_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeBytesSizeNoTag(stringArray_.getByteString(i));
        }
        size += dataSize;
        size += 1 * getStringArrayList().size();
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static QiwenSchema.QiwenSchemaInfo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static QiwenSchema.QiwenSchemaInfo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static QiwenSchema.QiwenSchemaInfo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static QiwenSchema.QiwenSchemaInfo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static QiwenSchema.QiwenSchemaInfo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static QiwenSchema.QiwenSchemaInfo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static QiwenSchema.QiwenSchemaInfo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static QiwenSchema.QiwenSchemaInfo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static QiwenSchema.QiwenSchemaInfo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static QiwenSchema.QiwenSchemaInfo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(QiwenSchema.QiwenSchemaInfo prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code QiwenSchemaInfo}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements QiwenSchema.QiwenSchemaInfoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return QiwenSchema.internal_static_QiwenSchemaInfo_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return QiwenSchema.internal_static_QiwenSchemaInfo_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                QiwenSchema.QiwenSchemaInfo.class, QiwenSchema.QiwenSchemaInfo.Builder.class);
      }

      // Construct using QiwenSchema.QiwenSchemaInfo.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        id_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        timestamp_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000002);
        fieldInt32_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        fieldFloat_ = 0F;
        bitField0_ = (bitField0_ & ~0x00000008);
        fieldDouble_ = 0D;
        bitField0_ = (bitField0_ & ~0x00000010);
        longArray_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000020);
        stringArray_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000040);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return QiwenSchema.internal_static_QiwenSchemaInfo_descriptor;
      }

      public QiwenSchema.QiwenSchemaInfo getDefaultInstanceForType() {
        return QiwenSchema.QiwenSchemaInfo.getDefaultInstance();
      }

      public QiwenSchema.QiwenSchemaInfo build() {
        QiwenSchema.QiwenSchemaInfo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public QiwenSchema.QiwenSchemaInfo buildPartial() {
        QiwenSchema.QiwenSchemaInfo result = new QiwenSchema.QiwenSchemaInfo(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.id_ = id_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.timestamp_ = timestamp_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.fieldInt32_ = fieldInt32_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.fieldFloat_ = fieldFloat_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.fieldDouble_ = fieldDouble_;
        if (((bitField0_ & 0x00000020) == 0x00000020)) {
          longArray_ = java.util.Collections.unmodifiableList(longArray_);
          bitField0_ = (bitField0_ & ~0x00000020);
        }
        result.longArray_ = longArray_;
        if (((bitField0_ & 0x00000040) == 0x00000040)) {
          stringArray_ = new com.google.protobuf.UnmodifiableLazyStringList(
              stringArray_);
          bitField0_ = (bitField0_ & ~0x00000040);
        }
        result.stringArray_ = stringArray_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof QiwenSchema.QiwenSchemaInfo) {
          return mergeFrom((QiwenSchema.QiwenSchemaInfo)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(QiwenSchema.QiwenSchemaInfo other) {
        if (other == QiwenSchema.QiwenSchemaInfo.getDefaultInstance()) return this;
        if (other.hasId()) {
          setId(other.getId());
        }
        if (other.hasTimestamp()) {
          setTimestamp(other.getTimestamp());
        }
        if (other.hasFieldInt32()) {
          setFieldInt32(other.getFieldInt32());
        }
        if (other.hasFieldFloat()) {
          setFieldFloat(other.getFieldFloat());
        }
        if (other.hasFieldDouble()) {
          setFieldDouble(other.getFieldDouble());
        }
        if (!other.longArray_.isEmpty()) {
          if (longArray_.isEmpty()) {
            longArray_ = other.longArray_;
            bitField0_ = (bitField0_ & ~0x00000020);
          } else {
            ensureLongArrayIsMutable();
            longArray_.addAll(other.longArray_);
          }
          onChanged();
        }
        if (!other.stringArray_.isEmpty()) {
          if (stringArray_.isEmpty()) {
            stringArray_ = other.stringArray_;
            bitField0_ = (bitField0_ & ~0x00000040);
          } else {
            ensureStringArrayIsMutable();
            stringArray_.addAll(other.stringArray_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        QiwenSchema.QiwenSchemaInfo parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (QiwenSchema.QiwenSchemaInfo) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional int64 id = 1;
      private long id_ ;
      /**
       * <code>optional int64 id = 1;</code>
       */
      public boolean hasId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional int64 id = 1;</code>
       */
      public long getId() {
        return id_;
      }
      /**
       * <code>optional int64 id = 1;</code>
       */
      public Builder setId(long value) {
        bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 id = 1;</code>
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = 0L;
        onChanged();
        return this;
      }

      // optional int64 timestamp = 2;
      private long timestamp_ ;
      /**
       * <code>optional int64 timestamp = 2;</code>
       */
      public boolean hasTimestamp() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional int64 timestamp = 2;</code>
       */
      public long getTimestamp() {
        return timestamp_;
      }
      /**
       * <code>optional int64 timestamp = 2;</code>
       */
      public Builder setTimestamp(long value) {
        bitField0_ |= 0x00000002;
        timestamp_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 timestamp = 2;</code>
       */
      public Builder clearTimestamp() {
        bitField0_ = (bitField0_ & ~0x00000002);
        timestamp_ = 0L;
        onChanged();
        return this;
      }

      // optional int32 field_int32 = 3;
      private int fieldInt32_ ;
      /**
       * <code>optional int32 field_int32 = 3;</code>
       */
      public boolean hasFieldInt32() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional int32 field_int32 = 3;</code>
       */
      public int getFieldInt32() {
        return fieldInt32_;
      }
      /**
       * <code>optional int32 field_int32 = 3;</code>
       */
      public Builder setFieldInt32(int value) {
        bitField0_ |= 0x00000004;
        fieldInt32_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 field_int32 = 3;</code>
       */
      public Builder clearFieldInt32() {
        bitField0_ = (bitField0_ & ~0x00000004);
        fieldInt32_ = 0;
        onChanged();
        return this;
      }

      // optional float field_float = 4;
      private float fieldFloat_ ;
      /**
       * <code>optional float field_float = 4;</code>
       */
      public boolean hasFieldFloat() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional float field_float = 4;</code>
       */
      public float getFieldFloat() {
        return fieldFloat_;
      }
      /**
       * <code>optional float field_float = 4;</code>
       */
      public Builder setFieldFloat(float value) {
        bitField0_ |= 0x00000008;
        fieldFloat_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional float field_float = 4;</code>
       */
      public Builder clearFieldFloat() {
        bitField0_ = (bitField0_ & ~0x00000008);
        fieldFloat_ = 0F;
        onChanged();
        return this;
      }

      // optional double field_double = 5;
      private double fieldDouble_ ;
      /**
       * <code>optional double field_double = 5;</code>
       */
      public boolean hasFieldDouble() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional double field_double = 5;</code>
       */
      public double getFieldDouble() {
        return fieldDouble_;
      }
      /**
       * <code>optional double field_double = 5;</code>
       */
      public Builder setFieldDouble(double value) {
        bitField0_ |= 0x00000010;
        fieldDouble_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional double field_double = 5;</code>
       */
      public Builder clearFieldDouble() {
        bitField0_ = (bitField0_ & ~0x00000010);
        fieldDouble_ = 0D;
        onChanged();
        return this;
      }

      // repeated int64 long_array = 6;
      private java.util.List<java.lang.Long> longArray_ = java.util.Collections.emptyList();
      private void ensureLongArrayIsMutable() {
        if (!((bitField0_ & 0x00000020) == 0x00000020)) {
          longArray_ = new java.util.ArrayList<java.lang.Long>(longArray_);
          bitField0_ |= 0x00000020;
         }
      }
      /**
       * <code>repeated int64 long_array = 6;</code>
       */
      public java.util.List<java.lang.Long>
          getLongArrayList() {
        return java.util.Collections.unmodifiableList(longArray_);
      }
      /**
       * <code>repeated int64 long_array = 6;</code>
       */
      public int getLongArrayCount() {
        return longArray_.size();
      }
      /**
       * <code>repeated int64 long_array = 6;</code>
       */
      public long getLongArray(int index) {
        return longArray_.get(index);
      }
      /**
       * <code>repeated int64 long_array = 6;</code>
       */
      public Builder setLongArray(
          int index, long value) {
        ensureLongArrayIsMutable();
        longArray_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int64 long_array = 6;</code>
       */
      public Builder addLongArray(long value) {
        ensureLongArrayIsMutable();
        longArray_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int64 long_array = 6;</code>
       */
      public Builder addAllLongArray(
          java.lang.Iterable<? extends java.lang.Long> values) {
        ensureLongArrayIsMutable();
        super.addAll(values, longArray_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int64 long_array = 6;</code>
       */
      public Builder clearLongArray() {
        longArray_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000020);
        onChanged();
        return this;
      }

      // repeated string string_array = 10;
      private com.google.protobuf.LazyStringList stringArray_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureStringArrayIsMutable() {
        if (!((bitField0_ & 0x00000040) == 0x00000040)) {
          stringArray_ = new com.google.protobuf.LazyStringArrayList(stringArray_);
          bitField0_ |= 0x00000040;
         }
      }
      /**
       * <code>repeated string string_array = 10;</code>
       */
      public java.util.List<java.lang.String>
          getStringArrayList() {
        return java.util.Collections.unmodifiableList(stringArray_);
      }
      /**
       * <code>repeated string string_array = 10;</code>
       */
      public int getStringArrayCount() {
        return stringArray_.size();
      }
      /**
       * <code>repeated string string_array = 10;</code>
       */
      public java.lang.String getStringArray(int index) {
        return stringArray_.get(index);
      }
      /**
       * <code>repeated string string_array = 10;</code>
       */
      public com.google.protobuf.ByteString
          getStringArrayBytes(int index) {
        return stringArray_.getByteString(index);
      }
      /**
       * <code>repeated string string_array = 10;</code>
       */
      public Builder setStringArray(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureStringArrayIsMutable();
        stringArray_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string string_array = 10;</code>
       */
      public Builder addStringArray(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureStringArrayIsMutable();
        stringArray_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string string_array = 10;</code>
       */
      public Builder addAllStringArray(
          java.lang.Iterable<java.lang.String> values) {
        ensureStringArrayIsMutable();
        super.addAll(values, stringArray_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string string_array = 10;</code>
       */
      public Builder clearStringArray() {
        stringArray_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000040);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string string_array = 10;</code>
       */
      public Builder addStringArrayBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureStringArrayIsMutable();
        stringArray_.add(value);
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:QiwenSchemaInfo)
    }

    static {
      defaultInstance = new QiwenSchemaInfo(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:QiwenSchemaInfo)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_QiwenSchemaInfo_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_QiwenSchemaInfo_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022qiwen-schema.proto\"\232\001\n\017QiwenSchemaInfo" +
      "\022\n\n\002id\030\001 \001(\003\022\021\n\ttimestamp\030\002 \001(\003\022\023\n\013field" +
      "_int32\030\003 \001(\005\022\023\n\013field_float\030\004 \001(\002\022\024\n\014fie" +
      "ld_double\030\005 \001(\001\022\022\n\nlong_array\030\006 \003(\003\022\024\n\014s" +
      "tring_array\030\n \003(\tB\rB\013QiwenSchema"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_QiwenSchemaInfo_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_QiwenSchemaInfo_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_QiwenSchemaInfo_descriptor,
              new java.lang.String[] { "Id", "Timestamp", "FieldInt32", "FieldFloat", "FieldDouble", "LongArray", "StringArray", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
